// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Navigation: typeof import('./components/Navigation.vue')['default']
    'Ph:barbellDuotone': typeof import('~icons/ph/barbell-duotone')['default']
    'Ph:barbellFill': typeof import('~icons/ph/barbell-fill')['default']
    'Ph:pencilLineDuotone': typeof import('~icons/ph/pencil-line-duotone')['default']
    'Ph:personSimpleRunDuotone': typeof import('~icons/ph/person-simple-run-duotone')['default']
    'Ph:trashDuotone': typeof import('~icons/ph/trash-duotone')['default']
    'Ph:trashSimple': typeof import('~icons/ph/trash-simple')['default']
  }
}

export { }
